# Generated by Django 4.0.4 on 2022-06-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_file',
            field=models.FileField(default='photos/user_avatar.png', upload_to='ProductFiles/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_image',
            field=models.ImageField(default='photos/user_avatar.png', upload_to='photos/'),
        ),
    ]
